### ISSUE TITLE
feat: pauser

### ISSUE THREAD

**Issue by ronag** [mcollina/fastq#14]
I have [a use case](https://github.com/mcollina/undici/blob/master/lib/client.js#L218-L221) where I have properties which are set than indicate that the queue should not run. Since there properties are set externally I have no way to react to these changes and manually call `pause()`.

I'm not sure exactly how but I would need some kind of API that would allow me to pass a function which indicates whether new tasks may be scheduled, e.g.

```js
const pauser = () => externalObject.paused
const queue = Q(worker, pauser)
```

This should work with `pause()` in a way where if the queue is explicitly paused or implicitly paused (through pauser) it should not schedule any new jobs.

If paused through pauser a normal `resume()` should resume it.

Would something like this make sense?

**Comment by ronag** [comment]
Something like this would probably be too slow...

**Comment by mcollina** [comment]
Unfortunately :(
