### ISSUE TITLE
Using argument.call

### ISSUE THREAD

**Issue by yonathan06** [mcollina/fastq#18]
I get the following error trying to register a plugin in [fastify v3](https://github.com/fastify/fastify), which uses [avvio](https://github.com/fastify/avvio) which uses this library:
`'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`
stack trace:
```sh
Plugin.exec (node_modules/avvio/plugin.js:129:17)
Boot.loadPlugin (node_modules/avvio/plugin.js:263:10)
Task.release (node_modules/fastq/queue.js:140:16)
worked (node_modules/fastq/queue.js:182:10)
node_modules/avvio/plugin.js:266:7
done (node_modules/avvio/plugin.js:198:5)
check (node_modules/avvio/plugin.js:222:9)
```

it seams that fastq is using `worker.call()`, when worker is an argument (assigned from `context` argument), but using `argument.call()` is desecrated from [es5](https://www.cuelogic.com/blog/the-hidden-life-of-javascript-function-properties#:~:text=caller%20%2C%20callee%20%2C%20and%20arguments%20properties,and%20removed%20in%20strict%20mode.&text=Through%20the%20function's%20constructor%20object,which%20exists%20in%20all%20functions)

Hope I'm not missing anything

**Comment by mcollina** [comment]
I'm totally lost on the error you are getting, can you please include an example to reproduce?

**Comment by yonathan06** [comment]
Error on my side, sorry for the trouble
