### ISSUE TITLE
Queue length meaning

### ISSUE THREAD

**Issue by simoneb** [mcollina/fastq#31]
I have a question about the behavior of the `length()` function, which is shown in [this line of code](https://github.com/mcollina/fastq/blob/master/test/test.js#L286) in the tests.

I assume the test shows how the length of the queue grows if tasks are queued but don't complete.

If the queue has concurrency 1 and one task is enqueued, I expect the length to be 0 because the task goes straight to executing, and that's correct in the test.

If a second task is enqueued, why does the length of the queue remain 0, since the first task has not completed? I would expect it to be 1. 

Either I don't understand how it's supposed to work or it seems to me that the `length()` function returns a value that is off by 1.

**Comment by mcollina** [comment]
The test is correct - length() returns the amount of tasks that are queued up, i.e. not started yet.

**Comment by simoneb** [comment]
So if concurrency is 1 and I queue 2 tasks without completing any yet, shouldn't it return 1 instead of 0?

**Comment by simoneb** [comment]
Ok apologies, my bad, I misread the test code and I thought that the size zero was after adding the second item. So it's me who was off by 1! The two zeroes are before any task is added and after 1 task is added, I thought it was after 1 task and after 2 tasks.
