### ISSUE TITLE
validate concurrency parameter

### ISSUE THREAD

**Issue by codekitchen** [mcollina/fastq#32]
I recently ran into [a bug in fast-glob](https://github.com/mrmlnc/fast-glob/pull/296) where it was setting `concurrency: 0` in some environments. This triggers a nasty situation where all work is just queued up forever and fastq silently never makes progress.

It might be good to validate the concurrency parameter and not allow a value less than 1.

**Comment by mcollina** [comment]
Good spot! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by KyleAMathews** [comment]
This should be closed
