### ISSUE TITLE
Support for batch-wise queueing

### ISSUE THREAD

**Issue by kamikazechaser** [mcollina/fastq#33]
> fastq is API compatible with async.queue

Async queue, supports batch-wise processing. i.e.

```js
const { queue } = require("async");

const q = queue(function (task, callback) {
  console.log(2 * task);
  callback();
}, 1);

// accepts array as arg for batchwise processing
q.push([2, 3, 4], function (err) {
  console.log("finished processing item");
});
```

Ref: https://github.com/caolan/async/blob/master/lib/internal/queue.js#L159

**Comment by mcollina** [comment]
Oh, that's kind of new. I'll remove the statement from the README then.

**Comment by kamikazechaser** [comment]
Sounds fair, adding some looping logic would probably remove the fast from fastq :grinning:.

**Comment by mcollina** [comment]
No, not really. The key problem is that we won't be able to pass arrays anymore as tasks to process. I think that's a feature worth preserving.
