### ISSUE TITLE
Error handler is always called if registered

### ISSUE THREAD

**Issue by xamgore** [mcollina/fastq#41]
> `queue.error(handler)`
> Set a global error handler. `handler(err, task)` will be called when any of the tasks return an error.

It seems to me that the error handler is called for each task at the finish. Let's check out the code:

<details>

```ts
  let queue: fastqueue.queue<T, R>

  function asyncWrapper(this: C, arg: T, cb: Done<R>) {
    worker.call(this, arg)
      .then(function (res: R) {
        cb(null, res)
      }, cb)
  }

  queue = fastqueue(asyncWrapper, concurrency)

  const barrier = () => new Promise<void>((resolve, reject) => {
    queue.drain = () => { console.log('resolve'); resolve()}
    queue.error(err => err !== null && reject(err))
  })

  queue.push(...)
```

</details>

We create a queue, register an error handler, and push some tasks later. Again, with references:

* `queue.error(...)` from the code above is [`self.error`](https://github.com/mcollina/fastq/blob/master/queue.js#L40), the definition is [on the line 174](https://github.com/mcollina/fastq/blob/master/queue.js#L174):
   ```js
  function error (handler) {
     errorHandler = handler
  }
  ```

* That `errorHandler` variable is then used at each [`push` method](https://github.com/mcollina/fastq/blob/master/queue.js#L97), each created `Task` now has `task.errorHandler`:

  ```js
  function push (value, done) {
    var current = cache.get()  // reusify(Task)

    current.context = context
    current.release = release
    current.value = value
    current.callback = done || noop
    current.errorHandler = errorHandler
    ...
   ```

* When a `Task` has finished, the method [`task.worked`](https://github.com/mcollina/fastq/blob/master/queue.js#L197) is called:

   ```js
  this.worked = function worked (err, result) {
     var callback = self.callback
     var errorHandler = self.errorHandler
     var val = self.value
     self.value = null
     self.callback = noop
     if (self.errorHandler) {
       errorHandler(err, val) // has been set previously, so it is called now
     }
     callback.call(self.context, err, result)
     self.release(self)
  }
   ```

What do you think about this? Am I missing something?

**Comment by mcollina** [comment]
This feature works exactly as intented. Use the push callback or the already promisified push method to intercept the error.

**Comment by gwh-cpnet** [comment]
If it is a feature, not a bug, please tweak the doc could be more accurate.
