### ISSUE TITLE
[Question] Pass function into task payload

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [mcollina/fastq#60]
I was wondering if there is any way to pass a function inside the payload pushed in the queue or if only serializable fields are maintained inside the object.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
