### ISSUE TITLE
Randomize queue?

### ISSUE THREAD

**Issue by catdevnull** [mcollina/fastq#79]
I have a program that first gets a bunch of links to download from different hosts, and then adds them to the queue to download. Something like

```js
for (const listLink of lists) {
  fetch(listLink).then(links => links.forEach(link => queue.push(link)))
}
```

 I would like to randomize the queue to distribute the load amongst hosts to maximize the download speeds. One way of doing this is having many queues, one for each host, but the problem is that depending on the N of hosts and M of concurrent tasks per queue, N*M might be too high and drop a bunch of connections and stuff.
 
Is there a simple way of doing this with fastq? Or is there another package that allows something like this?

**Comment by mcollina** [comment]
That problem is beyond what fastq is meant to solve.

I'd recommend you to take a look at undici.request and BalancedPool dispatcher.

**Comment by mcollina** [comment]
Unfortunately yes, I totally misunderstood your problem.
